name-template: '$NEXT_PATCH_VERSION🌈'
tag-template: 'jedis-$NEXT_PATCH_VERSION'
categories:
  - title: '🚀Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes

  $CHANGES
