version: 2.1

commands:

  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi

  abort_for_docs:
    steps:
      - run:
          name: Avoid tests doc docs
          command: |
            if [[ $CIRCLE_BRANCH == *docs ]]; then
              echo "Identified as a document PR, no testing required."
              circleci step halt
            fi

jobs:
  build-linux-8-jdk:
    docker:
      - image: cimg/openjdk:8.0

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - abort_for_docs
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - jedis-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: jedis-{{ checksum "pom.xml" }}

      - run: |
          sudo apt update
          sudo apt install -y stunnel

      - run: make circleci-install

      - run: TEST="" make test

      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

      - early_return_for_forked_pull_requests

  build_and_deploy:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - jedis-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run: mvn -s .circleci.settings.xml -DskipTests deploy

on-integ-branches: &on-integ-branches
  filters:
    branches:
      only:
        - master
        - /^\d+\.\d+.*$/

on-all-branches: &on-all-branches
  filters:
    branches:
      only:
        - /.*/

workflows:
  all-jdks:
    jobs:
      - build_and_deploy:
          <<: *on-integ-branches
          context:
            - common
          requires:
            - build-linux-8-jdk
      - build-linux-8-jdk:
          <<: *on-all-branches
